### ISSUE TITLE
starting container...

### ISSUE THREAD

**Issue by bblumberg** [NVIDIA-AI-IOT/isaac_ros_common#2]
Hi
I tried using run_dev.sh and as best I can tell it created the docker container correctly, but when it tries to launch the container, I get the following error:

docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/usr/lib/aarch64-linux-gnu/libcudnn.so.8.2.1" to rootfs at "/usr/lib/aarch64-linux-gnu/libcudnn.so.8.2.1" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
/xavier_ssd/projects/isaac_ros_common

The library does exist, so I am confused. 

Thanks,

bb

**Comment by hemalshahNV** [comment]
Strange. Are you running Jetpack 4.6 on this device? Reflashing it might help. The file you said exists? Do you know if you have set any default runtime in /etc/docker/daemon.json by any chance?

**Comment by bblumberg** [comment]
Before I did this, I upgraded to 4.6 via OTA (debian). Here is my /etc/docker/daemon.json:

{
    "runtimes": {
        "nvidia": {
            "path": "nvidia-container-runtime",
            "runtimeArgs": []
        }
    },
   "data-root": "/xavier_ssd/docker"
}

Thanks BTW for the speedy reply! It is much appreciated.

bb

**Comment by bblumberg** [comment]
I tracked down the issue and it turns out that libcudnn.so.8.2.1 already exists in the container so you don't need to be mounting the external version. I think it may get pulled in as part of the dusty-nv foxy image. In either case, the fix is to remove the line from the script. Otherwise, things seem good.

**Comment by hemalshahNV** [comment]
Hmm... that's a great find! I haven't found yet how libcudnn.so.8.2.1 is getting added to the container without the Docker mount. Dusty's Foxy image looks like it hasn't changed either. I'm trying to reproduce with a clean AGX Xavier now to see what I find.

**Comment by hemalshahNV** [comment]
On a clean AGX Xavier system, I am still having no trouble with /usr/lib/aarch64-linux-gnu/libcudnn.so.8.2.1 being "double mounted." I will leave it because we qualified against the mount included, but the mystery remains. Thanks for a crack in the case, though. If it comes up on another Jetson, we'll know what to look for.
