### ISSUE TITLE
Documentation suggestion...

### ISSUE THREAD

**Issue by bblumberg** [NVIDIA-AI-IOT/isaac_ros_common#4]
It would be great to add the desired directory structure for this and the other ROS2 packages that depend on this. For example:

workspaces/
      isaac_ros_common/
     isaac_ros_image_pipeline/

In fact, is that correct?

Thanks for making all of this available, and I hope my feedback is useful and not just an annoyance (actually it is probably a bit of both)

**Comment by hemalshahNV** [comment]
We tend to keep it as:

workspaces/isaac_ros-dev/ros_ws/src/
    isaac_ros_common/
    isaac_ros_image_pipeline/

and then invoke `colcon build` only from workspaces/isaac_ros-dev/ros_ws

**Comment by hemalshahNV** [comment]
Your feedback is very helpful. Thank you for taking the time to send it to us.

**Comment by bblumberg** [comment]
Thanks, so they should be treated as packages living in the src directory. That makes sense.
